language: go
go:
- tip
notifications:
  email: false
env:
  secure: hA4OYACtls6UCfrfrb0l/nZp8gs4ikQ9hAjCRKf/XGHXBbKBijw4XLj5qSB7FWuGtaPZw38JrlV6cIG3JxO4E+VOrSZKtJIGnnp6i7Ez1bO33B5yC0fX9zkguoWAULYgEYb+uT+hWB/4URXdhcJgZumezONKx+cxjc2lrcG7NlIDH8LKn5ctCnLMx5RGWCpnc7z9TaIuYWaUu6zl8+h2DJmsSkYfo6MAl72KIQ7MILK7t1DD+hDA/Yk+rbvEHKWWOsdriB9OzLm5j2o5HLAy1afDH7UCX8gqNtUWV3k79PaVncegfXRMecBPFiOiLWUGOhLVZ8UrP8ge+j1UCWyIRged56K+kmWg724iHQCwP2YR9o8qhl13vQO5vX1cu/Bz+d4NgAapoXTdvtBKoNG4uq9x2dxs1BSr5ipa9FbxPuye/e3JKlOq7kAZapQ4PqV9eK1iWZFjxkzhSE4LGNK64EWMXX/1uKSMHQeyWGyhYg0EKhUXU5A9iZK2+4A4TE7Dq2FwtI8ebbCglwUtdt+Swozry46IHe30k26GpaA9H8BiprkWRL8H9k7cdGAvPeGorluS/q30Yr54BSdh7RPfGVoMOzlaoID3sQ4YzZ3YweCpTxi173adC9yDZi3y1UtgtJvTkqr+VCgvUv1G/jzhWyksvHs384SW8TXTsuSLQEg=
