language: go
go:
- tip
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get -t -v ./...
script:
# - go test -v -race -cover -coverprofile=coverage.out
# - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  # $COVERALLS_TOKEN
notifications:
  email: false
env:
  secure: JPdYX6fNO3r/lrOJ0CLtTVeo/QTioeKtVYXjY8v0Ubdzu6Ju/DJD+c6+seByYr+f7QuYwzPNawI9n9aVfdUP4pRg4pc6njpCjCItsHErOPEA9BFGYMV7E53K1RX9OfR+oclW2H6RWNj3V7LkGE5sngXuNTIXxi3irM3Hs6SyXeF1bXk3PaoQuan6i3TI4jbGFRkBmn8A1LQ3ngXCLrC79SnTNjrND138h9/0X1QdAyhpdTWUmxFyUkfDG63WLdEEr7rZgE3rc0x2kbVbrD3YjIbexDd2NqIIv6u5OuQG5ceanSAg0IZjhObyy0l/tibWnrUuF19LhvzJ/UQQHzFeZf7XOEBKrj5SGE5qVbnzRa0x/LJ2FA1eFhz5dXuTMds2X6PPCIdpdc4aWhj1Gy61ufKqdhwp0cDD2wfW6OvtMAXiBzSFGaIxAWewzndDWtoVWFGDcJpl0xl/QJSyTJ+WZw1mi7BdGFWKPBWijCJ+ZqkhsdY8d/dj9e4uMsVGBKcFLYvoAvfn5rsnIDgUKlIQatGEdEcRYkUmgRrlRlUM3nI/LwslPDjRDgc/S+xJARxJwyOFDdeXTMZEFqkr2pu0BDpcVIVh4yh26R1BsNxrh2tcbup1nlszzDZAyl+rZu+HW8Wemo1AcfAuTSvQvUHkbTmlaK5ASEH8aR2n4U84Qtg=
